version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/vartur
      - NODE_ENV=production
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    # network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=vartur
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    # volumes:
    #   - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
# volumes:
#   mysql-data:
